# Generated by Django 3.1.7 on 2021-04-20 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_productname_capitalize'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='data_updated',
            new_name='date_updated',
        ),
    ]
